### ISSUE TITLE
msync git clone with 'path already exists'

### ISSUE THREAD

**Issue by fatmcgav** [puppet-community/modulesync#55]
When attempting to run msync, the first run works as expected. 
However any further runs fail, as shown here: https://gist.github.com/fatmcgav/98629849f717c1dfa901

Git version = 2.5.0
OSX 10.10.4

**Comment by cmurphy** [comment]
@fatmcgav can you see if #56 fixes your issue?

**Comment by danzilio** [comment]
:+1:

**Comment by fatmcgav** [comment]
@cmurphy Cheers for the quick turn around... I'll give it a go in the morning. 

Cheers 
Gav

**Comment by fatmcgav** [comment]
@cmurphy Yep, that does the trick :)
